### ISSUE TITLE
How do I change the target environment in esbuild

### ISSUE THREAD

**Issue by oyedejioyewole** [caoxiemeihao/nuxt-plugin-electron#19]
In the `main.ts` file used for loading Electron, I used a top-level await statement

```js
const response = await somePromiseFunction()
```

and when I saved the file, I got the error

```log
<stdin>:16:19: ERROR: Top-level await is not available in the configured target environment ("node14")
```

I was wondering if there was a way of changing the target environment

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-electron-plugin#configuration

<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/227555661-9b2bf18d-814f-4d57-9224-67ff4ba3eb09.png">

```ts
export default defineNuxtConfig({
  modules: [
    'nuxt-electron',
  ],
  electron: {
    transformOptions: {}, // here
  },
})
```

**Comment by OyewoleOyedeji** [comment]
@caoxiemeihao I then get this error

`<stdin>:16:19: ERROR: Top-level await is currently not supported with the "cjs" output format`

**Comment by caoxiemeihao** [comment]
`top-level await` can be used `ESM` format only! At present, Electron can only support `CJS` format.
